### ISSUE TITLE
Skia link is dead

### ISSUE THREAD

**Issue by shujaatak** [QtSkia/QtSkia#1]
In the 3rdparty when I click on skia(https://github.com/google/skia/tree/7ecd6fbe8ab22e5141a4f3ca8d6f036dd2461a54), I get the following message:
"This is not the web page you are looking for"

I would suggest that please import skia repository to your account and then link it in the QtSkia.

**Comment by jaredtao** [comment]
thanks, i  will link skia to my repository.

**Comment by jaredtao** [comment]
i had link to my repository
